name: CI/CD 🚀

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  AZURE_WEBAPP_NAME: WhatTimeIsIt
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore ./WhatTimeIsIt.sln

      - name: Build Solution
        run: dotnet build ./WhatTimeIsIt.sln --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test ./WhatTimeIsIt.sln --no-build --configuration Release --verbosity normal

      - name: Publish
        run: dotnet publish ./WhatTimeIsIt.Api/WhatTimeIsIt.Api.csproj --configuration Release --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-package
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    if: github.event_name == 'push'  # Only deploy on push (not PR)
    runs-on: ubuntu-latest
    needs: build  # Only deploy after build succeeds
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-package
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"